### ISSUE TITLE
No audio 

### ISSUE THREAD

**Issue by EngAUD** [zeffii/Supercollider3_tutorials_code#3]
Hi!!

I attempted to use MIDI on supercollider however I could not hear any audio. I could see the notes in to post window but there was just no sound.

Any help would be appreciated

**Comment by elifieldsteel** [comment]
Yes, I saw your comment on YouTube.

As should be obvious, it is not possible to solve your problem without
seeing your code and knowing more about your software/hardware setup.
Imagine calling an auto mechanic and saying "my car is broken, what's wrong
with it?"

Is the server booted? Do you see signal on the SC output level GUI? Is the
volume turned up on your computer or audio interface? Do you see any error
messages? Are you able to produce any sound at all?

Eli

**Comment by EngAUD** [comment]
Thank you so much for responding. I have managed to get sound out now!
